export const languages = {
  en: {
    translation: {
      Sign: 'Sign',
      History: 'History',
      mainnet: 'mainnet',
      testnet: 'testnet',
      'Wallets Manager': 'Wallets Manager',
      'Contacts Manager': 'Contacts Manager',
      Logout: 'Logout',
      'Password is incorect': 'Password is incorect',
      'Password error': 'Password error',
      'Password is required': 'Password is required',
      'Welcome Back': 'Welcome Back',
      'Field Is Required': 'Field Is Required',
      Unlock: 'Unlock',
      'Word is required': 'Word is required',
      'Name is required': 'Name is required',
      'Password must be at least 6 characters':
        'Password must be at least 6 characters',
      'Passwords must match': 'Passwords must match',
      'Confirm Password is required': 'Confirm Password is required',
      'Invalid word': 'Invalid word',
      'Creating wallet failed': 'Creating wallet failed',
      'Password match error': 'Password match error',
      'Wallet Name': 'Wallet Name',
      'Create Password': 'Create Password',
      'Confirm Password': 'Confirm Password',
      Next: 'Next',
      'Contact Name and Address Are Required':
        'Contact Name and Address Are Required',
      Name: 'Name',
      Address: 'Address',
      'Contact Name': 'Contact Name',
      'Contact Address': 'Contact Address',
      'Go Back': 'Go Back',
      'Add Contact': 'Add Contact',
      'Wallet Name Is Required': 'Wallet Name Is Required',
      'Address Copied': `Address Copied`,
      'Wallet Manager': 'Wallet Manager',
      'New Wallet Name': 'New Wallet Name',
      'Add Wallet': 'Add Wallet',
      'Contacts List': 'Contacts List',
      'Select a contact to send CLORE to': 'Select a contact to send CLORE to',
      Cancel: 'Cancel',
      'Message is required': 'Message is required',
      'Message signed': 'Message signed',
      'Copied Information': 'Copied Information',
      'Proof of Holdings': 'Proof of Holdings',
      'Message (Required)': 'Message (Required)',
      Signature: 'Signature',
      Message: 'Message',
      'Waiting for CLORE Blockchain': 'Waiting for CLORE Blockchain',
      'Transaction Failed': 'Transaction Failed',
      'Transaction Complete': 'Transaction Complete',
      Clipboard: 'Clipboard',
      'Copied Address': 'Copied Address',
      'Address Is Required': 'Address Is Required',
      Amount: 'Amount',
      'Amount Is Required': 'Amount Is Required',
      MAX: 'MAX',
      'Network Fee': 'Network Fee',
      Send: 'Send',
      'Wallets List': 'Wallets List',
      'Select a wallet': 'Select a wallet',
      Wallet: 'Wallet',
      Welcome: 'Welcome',
      'Create a new wallet or Recovery an existing wallet':
        'Create a new wallet or Recovery an existing wallet',
      'Create a new wallet': 'Create a new wallet',
      'Recover an existing wallet': 'Recover an existing wallet',
      'New Recovery Phrase': 'New Recovery Phrase',
      'Wallet Created': 'Wallet Created',
      'Store your recovery phrase in a safe & secure place':
        'Store your recovery phrase in a safe & secure place',
      Step: 'Step',
      'Account was created successfully!': 'Account was created successfully!',
      'Welcome Clore Network': 'Welcome Clore Network',
      Finish: 'Finish',
      'Copied to clipboard': 'Copied to clipboard',
      'Your recovery phrase has been copied to the clipboard.':
        'Your recovery phrase has been copied to the clipboard.',
      'Invalid Mnemonic': 'Invalid Mnemonic',
      'Please enter a valid mnemonic phrase':
        'Please enter a valid mnemonic phrase',
      'Must be 12 words separated by spaces.':
        'Must be 12 words separated by spaces.',
      '12-Word Mnemonic': '12-Word Mnemonic',
      'Copy to clipboard': 'Copy to clipboard',
      'DO NOT share your recovery phrase with ANYONE.':
        'DO NOT share your recovery phrase with ANYONE.',
      'Please stay vigilant against phishing attacks at all times.':
        'Please stay vigilant against phishing attacks at all times.',
      Error: 'Error',
      Password: 'Password',
    },
  },
  es: {
    translation: {
      Sign: 'Firmar',
      History: 'Historia',
      mainnet: 'red principal',
      testnet: 'red de pruebas',
      'Wallets Manager': 'Gestor de Carteras',
      'Contacts Manager': 'Gestor de Contactos',
      Logout: 'Cerrar Sesión',
      'Password is incorrect': 'La contraseña es incorrecta',
      'Password error': 'Error de contraseña',
      'Password is required': 'Se requiere contraseña',
      'Welcome Back': 'Bienvenido de Nuevo',
      'Field Is Required': 'El campo es obligatorio',
      Unlock: 'Desbloquear',
      'Word is required': 'Se requiere palabra',
      'Name is required': 'Se requiere nombre',
      'Password must be at least 6 characters':
        'La contraseña debe tener al menos 6 caracteres',
      'Passwords must match': 'Las contraseñas deben coincidir',
      'Confirm Password is required': 'Se requiere confirmación de contraseña',
      'Invalid word': 'Palabra inválida',
      'Creating wallet failed': 'Error al crear la cartera',
      'Password match error': 'Error de coincidencia de contraseña',
      'Wallet Name': 'Nombre de la Cartera',
      'Create Password': 'Crear Contraseña',
      'Confirm Password': 'Confirmar Contraseña',
      Next: 'Siguiente',
      'Contact Name and Address Are Required':
        'Se requieren nombre y dirección del contacto',
      Name: 'Nombre',
      Address: 'Dirección',
      'Contact Name': 'Nombre del Contacto',
      'Contact Address': 'Dirección del Contacto',
      'Go Back': 'Regresar',
      'Add Contact': 'Añadir Contacto',
      'Wallet Name Is Required': 'Se requiere Nombre de la Cartera',
      'Address Copied': 'Dirección Copiada',
      'Wallet Manager': 'Gestor de Carteras',
      'New Wallet Name': 'Nuevo Nombre de Cartera',
      'Add Wallet': 'Añadir Cartera',
      'Contacts List': 'Lista de Contactos',
      'Select a contact to send CLORE to':
        'Seleccione un contacto para enviar CLORE',
      Cancel: 'Cancelar',
      'Message is required': 'Se requiere mensaje',
      'Message signed': 'Mensaje firmado',
      'Copied Information': 'Información Copiada',
      'Proof of Holdings': 'Prueba de Tenencias',
      'Message (Required)': 'Mensaje (Obligatorio)',
      Signature: 'Firma',
      Message: 'Mensaje',
      'Waiting for CLORE Blockchain': 'Esperando la Blockchain de CLORE',
      'Transaction Failed': 'Transacción Fallida',
      'Transaction Complete': 'Transacción Completada',
      Clipboard: 'Portapapeles',
      'Copied Address': 'Dirección Copiada',
      'Address Is Required': 'Se requiere Dirección',
      Amount: 'Cantidad',
      'Amount Is Required': 'Se requiere Cantidad',
      MAX: 'MÁX',
      'Network Fee': 'Tarifa de Red',
      Send: 'Enviar',
      'Wallets List': 'Lista de Carteras',
      'Select a wallet': 'Seleccione una cartera',
      Wallet: 'Cartera',
      Welcome: 'Bienvenido',
      'Create a new wallet or Recover an existing wallet':
        'Crear una nueva cartera o Recuperar una existente',
      'Create a new wallet': 'Crear una nueva cartera',
      'Recover an existing wallet': 'Recuperar una cartera existente',
      'New Recovery Phrase': 'Nueva Frase de Recuperación',
      'Wallet Created': 'Cartera Creada',
      'Store your recovery phrase in a safe & secure place':
        'Guarde su frase de recuperación en un lugar seguro',
      Step: 'Paso',
      'Account was created successfully!': '¡Cuenta creada con éxito!',
      'Welcome Clore Network': 'Bienvenido a la Red Clore',
      Finish: 'Finalizar',
      'Copied to clipboard': 'Copiado al portapapeles',
      'Your recovery phrase has been copied to the clipboard.':
        'Su frase de recuperación ha sido copiada al portapapeles.',
      'Invalid Mnemonic': 'Mnemónico Inválido',
      'Please enter a valid mnemonic phrase':
        'Por favor, introduzca una frase mnemónica válida',
      'Must be 12 words separated by spaces.':
        'Debe ser de 12 palabras separadas por espacios.',
      '12-Word Mnemonic': 'Mnemónico de 12 Palabras',
      'Copy to clipboard': 'Copiar al portapapeles',
      'DO NOT share your recovery phrase with ANYONE.':
        'NO comparta su frase de recuperación con NADIE.',
      'Please stay vigilant against phishing attacks at all times.':
        'Manténgase alerta contra los ataques de phishing en todo momento.',
      Error: 'Error',
      Password: 'Contraseña',
    },
  },
  ru: {
    translation: {
      Sign: 'Подписать',
      History: 'История',
      mainnet: 'основная сеть',
      testnet: 'тестовая сеть',
      'Wallets Manager': 'Менеджер Кошельков',
      'Contacts Manager': 'Менеджер Контактов',
      Logout: 'Выйти',
      'Password is incorrect': 'Неверный пароль',
      'Password error': 'Ошибка пароля',
      'Password is required': 'Требуется пароль',
      'Welcome Back': 'Добро пожаловать обратно',
      'Field Is Required': 'Поле обязательно для заполнения',
      Unlock: 'Разблокировать',
      'Word is required': 'Требуется слово',
      'Name is required': 'Требуется имя',
      'Password must be at least 6 characters':
        'Пароль должен содержать не менее 6 символов',
      'Passwords must match': 'Пароли должны совпадать',
      'Confirm Password is required': 'Требуется подтверждение пароля',
      'Invalid word': 'Недопустимое слово',
      'Creating wallet failed': 'Не удалось создать кошелек',
      'Password match error': 'Ошибка совпадения паролей',
      'Wallet Name': 'Имя Кошелька',
      'Create Password': 'Создать Пароль',
      'Confirm Password': 'Подтвердить Пароль',
      Next: 'Далее',
      'Contact Name and Address Are Required': 'Требуются Имя и Адрес Контакта',
      Name: 'Имя',
      Address: 'Адрес',
      'Contact Name': 'Имя Контакта',
      'Contact Address': 'Адрес Контакта',
      'Go Back': 'Вернуться',
      'Add Contact': 'Добавить Контакт',
      'Wallet Name Is Required': 'Требуется Имя Кошелька',
      'Address Copied': 'Адрес Скопирован',
      'Wallet Manager': 'Менеджер Кошельков',
      'New Wallet Name': 'Новое Имя Кошелька',
      'Add Wallet': 'Добавить Кошелек',
      'Contacts List': 'Список Контактов',
      'Select a contact to send CLORE to':
        'Выберите контакт для отправки CLORE',
      Cancel: 'Отмена',
      'Message is required': 'Требуется сообщение',
      'Message signed': 'Сообщение подписано',
      'Copied Information': 'Информация Скопирована',
      'Proof of Holdings': 'Доказательство Владения',
      'Message (Required)': 'Сообщение (Обязательно)',
      Signature: 'Подпись',
      Message: 'Сообщение',
      'Waiting for CLORE Blockchain': 'Ожидание блокчейна CLORE',
      'Transaction Failed': 'Транзакция Неудачна',
      'Transaction Complete': 'Транзакция Завершена',
      Clipboard: 'Буфер Обмена',
      'Copied Address': 'Адрес Скопирован',
      'Address Is Required': 'Требуется Адрес',
      Amount: 'Сумма',
      'Amount Is Required': 'Требуется Сумма',
      MAX: 'МАКС',
      'Network Fee': 'Комиссия Сети',
      Send: 'Отправить',
      'Wallets List': 'Список Кошельков',
      'Select a wallet': 'Выберите кошелек',
      Wallet: 'Кошелек',
      Welcome: 'Добро пожаловать',
      'Create a new wallet or Recover an existing wallet':
        'Создать новый кошелек или восстановить существующий',
      'Create a new wallet': 'Создать новый кошелек',
      'Recover an existing wallet': 'Восстановить существующий кошелек',
      'New Recovery Phrase': 'Новая Фраза Восстановления',
      'Wallet Created': 'Кошелек Создан',
      'Store your recovery phrase in a safe & secure place':
        'Храните вашу фразу восстановления в безопасном месте',
      Step: 'Шаг',
      'Account was created successfully!': 'Аккаунт успешно создан!',
      'Welcome Clore Network': 'Добро пожаловать в сеть Clore',
      Finish: 'Завершить',
      'Copied to clipboard': 'Скопировано в буфер обмена',
      'Your recovery phrase has been copied to the clipboard.':
        'Ваша фраза восстановления скопирована в буфер обмена.',
      'Invalid Mnemonic': 'Неверный Мнемоник',
      'Please enter a valid mnemonic phrase':
        'Пожалуйста, введите действительную мнемоническую фразу',
      'Must be 12 words separated by spaces.':
        'Должно быть 12 слов, разделенных пробелами.',
      '12-Word Mnemonic': '12-Словная Мнемоника',
      'Copy to clipboard': 'Копировать в буфер обмена',
      'DO NOT share your recovery phrase with ANYONE.':
        'НИКОМУ не сообщайте вашу фразу восстановления.',
      'Please stay vigilant against phishing attacks at all times.':
        'Всегда будьте настороже от фишинговых атак.',
      Error: 'Ошибка',
      Password: 'Пароль',
    },
  },
  ch: {
    translation: {
      Sign: '签名',
      History: '历史',
      mainnet: '主网',
      testnet: '测试网',
      'Wallets Manager': '钱包管理',
      'Contacts Manager': '联系人管理',
      Logout: '登出',
      'Password is incorrect': '密码不正确',
      'Password error': '密码错误',
      'Password is required': '需要密码',
      'Welcome Back': '欢迎回来',
      'Field Is Required': '该字段为必填项',
      Unlock: '解锁',
      'Word is required': '需要词语',
      'Name is required': '需要名称',
      'Password must be at least 6 characters': '密码至少需要6个字符',
      'Passwords must match': '密码必须匹配',
      'Confirm Password is required': '需要确认密码',
      'Invalid word': '无效的词语',
      'Creating wallet failed': '创建钱包失败',
      'Password match error': '密码匹配错误',
      'Wallet Name': '钱包名称',
      'Create Password': '创建密码',
      'Confirm Password': '确认密码',
      Next: '下一步',
      'Contact Name and Address Are Required': '联系人名称和地址是必须的',
      Name: '名称',
      Address: '地址',
      'Contact Name': '联系人名称',
      'Contact Address': '联系人地址',
      'Go Back': '返回',
      'Add Contact': '添加联系人',
      'Wallet Name Is Required': '需要钱包名称',
      'Address Copied': '地址已复制',
      'Wallet Manager': '钱包管理',
      'New Wallet Name': '新钱包名称',
      'Add Wallet': '添加钱包',
      'Contacts List': '联系人列表',
      'Select a contact to send CLORE to': '选择一个联系人发送CLORE',
      Cancel: '取消',
      'Message is required': '需要消息',
      'Message signed': '消息已签名',
      'Copied Information': '复制的信息',
      'Proof of Holdings': '持有证明',
      'Message (Required)': '消息（必填）',
      Signature: '签名',
      Message: '消息',
      'Waiting for CLORE Blockchain': '等待CLORE区块链',
      'Transaction Failed': '交易失败',
      'Transaction Complete': '交易完成',
      Clipboard: '剪贴板',
      'Copied Address': '已复制地址',
      'Address Is Required': '需要地址',
      Amount: '金额',
      'Amount Is Required': '需要金额',
      MAX: '最大值',
      'Network Fee': '网络费',
      Send: '发送',
      'Wallets List': '钱包列表',
      'Select a wallet': '选择一个钱包',
      Wallet: '钱包',
      Welcome: '欢迎',
      'Create a new wallet or Recover an existing wallet':
        '创建新钱包或恢复现有钱包',
      'Create a new wallet': '创建新钱包',
      'Recover an existing wallet': '恢复现有钱包',
      'New Recovery Phrase': '新恢复短语',
      'Wallet Created': '钱包已创建',
      'Store your recovery phrase in a safe & secure place':
        '将您的恢复短语存放在安全的地方',
      Step: '步骤',
      'Account was created successfully!': '账户已成功创建！',
      'Welcome Clore Network': '欢迎来到Clore网络',
      Finish: '完成',
      'Copied to clipboard': '已复制到剪贴板',
      'Your recovery phrase has been copied to the clipboard.':
        '您的恢复短语已被复制到剪贴板。',
      'Invalid Mnemonic': '无效的助记词',
      'Please enter a valid mnemonic phrase': '请输入有效的助记词短语',
      'Must be 12 words separated by spaces.': '必须是由空格分隔的12个单词。',
      '12-Word Mnemonic': '12字助记词',
      'Copy to clipboard': '复制到剪贴板',
      'DO NOT share your recovery phrase with ANYONE.':
        '不要与任何人分享您的恢复短语。',
      'Please stay vigilant against phishing attacks at all times.':
        '请随时保持警惕，防范网络钓鱼攻击。',
      Error: '错误',
      Password: '密码',
    },
  },
  tur: {
    translation: {
      Sign: 'İmzala',
      History: 'Tarih',
      mainnet: 'ana ağ',
      testnet: 'test ağı',
      'Wallets Manager': 'Cüzdan Yöneticisi',
      'Contacts Manager': 'Kişi Yöneticisi',
      Logout: 'Çıkış Yap',
      'Password is incorrect': 'Şifre yanlış',
      'Password error': 'Şifre hatası',
      'Password is required': 'Şifre gerekli',
      'Welcome Back': 'Tekrar Hoşgeldiniz',
      'Field Is Required': 'Alan Gereklidir',
      Unlock: 'Kilidi Aç',
      'Word is required': 'Kelime gerekli',
      'Name is required': 'İsim gerekli',
      'Password must be at least 6 characters':
        'Şifre en az 6 karakter olmalıdır',
      'Passwords must match': 'Şifreler eşleşmelidir',
      'Confirm Password is required': 'Şifre onayı gerekli',
      'Invalid word': 'Geçersiz kelime',
      'Creating wallet failed': 'Cüzdan oluşturma başarısız',
      'Password match error': 'Şifre eşleşme hatası',
      'Wallet Name': 'Cüzdan Adı',
      'Create Password': 'Şifre Oluştur',
      'Confirm Password': 'Şifreyi Onayla',
      Next: 'Sonraki',
      'Contact Name and Address Are Required': 'Kişi Adı ve Adresi Gereklidir',
      Name: 'Ad',
      Address: 'Adres',
      'Contact Name': 'Kişi Adı',
      'Contact Address': 'Kişi Adresi',
      'Go Back': 'Geri Dön',
      'Add Contact': 'Kişi Ekle',
      'Wallet Name Is Required': 'Cüzdan Adı Gereklidir',
      'Address Copied': 'Adres Kopyalandı',
      'Wallet Manager': 'Cüzdan Yöneticisi',
      'New Wallet Name': 'Yeni Cüzdan Adı',
      'Add Wallet': 'Cüzdan Ekle',
      'Contacts List': 'Kişi Listesi',
      'Select a contact to send CLORE to':
        'CLORE göndermek için bir kişi seçin',
      Cancel: 'İptal',
      'Message is required': 'Mesaj gerekli',
      'Message signed': 'Mesaj imzalandı',
      'Copied Information': 'Bilgi Kopyalandı',
      'Proof of Holdings': 'Varlık Kanıtı',
      'Message (Required)': 'Mesaj (Gerekli)',
      Signature: 'İmza',
      Message: 'Mesaj',
      'Waiting for CLORE Blockchain': 'CLORE Blockchain Bekleniyor',
      'Transaction Failed': 'İşlem Başarısız',
      'Transaction Complete': 'İşlem Tamamlandı',
      Clipboard: 'Pano',
      'Copied Address': 'Adres Kopyalandı',
      'Address Is Required': 'Adres Gerekli',
      Amount: 'Miktar',
      'Amount Is Required': 'Miktar Gerekli',
      MAX: 'MAKS',
      'Network Fee': 'Ağ Ücreti',
      Send: 'Gönder',
      'Wallets List': 'Cüzdan Listesi',
      'Select a wallet': 'Bir cüzdan seç',
      Wallet: 'Cüzdan',
      Welcome: 'Hoşgeldiniz',
      'Create a new wallet or Recover an existing wallet':
        'Yeni bir cüzdan oluşturun veya mevcut bir cüzdanı kurtarın',
      'Create a new wallet': 'Yeni bir cüzdan oluştur',
      'Recover an existing wallet': 'Mevcut bir cüzdanı kurtar',
      'New Recovery Phrase': 'Yeni Kurtarma İfadesi',
      'Wallet Created': 'Cüzdan Oluşturuldu',
      'Store your recovery phrase in a safe & secure place':
        'Kurtarma ifadenizi güvenli ve emniyetli bir yerde saklayın',
      Step: 'Adım',
      'Account was created successfully!': 'Hesap başarıyla oluşturuldu!',
      'Welcome Clore Network': 'Clore Ağına Hoşgeldiniz',
      Finish: 'Bitir',
      'Copied to clipboard': 'Panoya kopyalandı',
      'Your recovery phrase has been copied to the clipboard.':
        'Kurtarma ifadeniz panoya kopyalandı.',
      'Invalid Mnemonic': 'Geçersiz Mnemonik',
      'Please enter a valid mnemonic phrase':
        'Lütfen geçerli bir mnemonik ifade girin',
      'Must be 12 words separated by spaces.':
        'Boşluklarla ayrılmış 12 kelime olmalıdır.',
      '12-Word Mnemonic': '12-Kelimelik Mnemonik',
      'Copy to clipboard': 'Panoya kopyala',
      'DO NOT share your recovery phrase with ANYONE.':
        'Kurtarma ifadenizi KİMSEYLE paylaşmayın.',
      'Please stay vigilant against phishing attacks at all times.':
        'Her zaman kimlik avı saldırılarına karşı tetikte olun.',
      Error: 'Hata',
      Password: 'Şifre',
    },
  },
};
